__author__ = 'salmaan'

blocked = {"youtube.com",
           "m.youtube.com",
           "imgur.com",
           "i.imgur.com",
           "imgflip.com",
           "flipkart.com",
           "snapdeal.com",
           "ebay.com",
           "blogs.wsj.com",
           "pbs.twimg.com",
           "twitter.com",
           "buzzfeed.com",
           "ptinews.com",
           "vine.co",
           "indigogo.com",
           "en.wikipedia.com",
           "self.india",
           "niticentral.com",
           "nytimes.com",
           "youtu.be",
           "saddahaq.com",
           "amazon.in",
           "liveleak.com",
           "m.liveleak.com",
           "vid.me",
           "github.com",
           "streamable.com",
           "reddit.com",
           "np.reddit.com",
           "dropbox.com",
           "raiot.in",
           "socialblade.com",
           "fortune.com"
           "soundcloud.com"
}
